name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - master

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: theratec/therapp-android
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          submodules: true
          
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '7.0.x'

      - name: Add .NET Workloads
        run: dotnet workload install maui-ios maui-android maui-maccatalyst ios android maccatalyst

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
